/** ARRAY DE MONSTROS */
export const monstros = [

  {
    level: 1,
    name: 'Snail',
    hp: 2,
    atk: 1,
    xp: 1,
    meso: 2,
    img: 'img/monsters/monster_snail.webp',
  },
  {
    level: 1,
    name: 'Blue Snail',
    hp: 5,
    atk: 3,
    xp: 3,
    meso: 4,
    img: 'img/monsters/monster_bluesnail.webp',
  },
  {
    level: 1,
    name: 'Shroom',
    hp: 9,
    atk: 7,
    xp: 5,
    meso: 5,
    img: 'img/monsters/monster_shroom.webp',
  },
  {
    level: 1,
    name: 'Tino',
    hp: 12,
    atk: 10,
    xp: 9,
    meso: 7,
    img: 'img/monsters/monster_tino.webp',
  },
  {
    level: 1,
    name: 'Stump',
    hp: 20,
    atk: 6,
    xp: 5,
    meso: 1,
    img: 'img/monsters/monster_stump.webp',
  },
  {
    level: 1,
    name: 'Orange Mushroom',
    hp: 24,
    atk: 7,
    xp: 7,
    meso: 1,
    img: 'img/monsters/monster_orangemushroom.webp',
  },
  {
    level: 1,
    name: 'Slime',
    hp: 28,
    atk: 8,
    xp: 9,
    meso: 1,
    img: 'img/monsters/monster_slime.webp',
  },
  {
    level: 1,
    name: 'Murukum',
    hp: 32,
    atk: 9,
    xp: 9,
    meso: 1,
    img: 'img/monsters/monster_murukun.webp',
  },
  {
    level: 1,
    name: 'Tiguru',
    hp: 36,
    atk: 10,
    xp: 11,
    meso: 1,
    img: 'img/monsters/monster_tiguru.webp',
  },
  {
    level: 1,
    name: 'Green Mushroom',
    hp: 40,
    atk: 10,
    xp: 13,
    meso: 1,
    img: 'img/monsters/monster_greenmushroom.webp',
  },
  {
    level: 1,
    name: '[BOSS] Mano',
    hp: 50,
    atk: 15,
    xp: 30,
    meso: 1,
    img: 'img/monsters/monster_mano.webp',
  },
  {
    level: 1,
    name: 'Stranger Pig',
    hp: 24,
    atk: 1,
    xp: 15,
    meso: 1,
    img: 'img/monsters/monster_strangerpig.webp',
  },
  {
    level: 1,
    name: 'Horny Mushroom',
    hp: 26,
    atk: 1,
    xp: 17,
    meso: 1,
    img: 'img/monsters/monster_hornymushroom.webp',
  },
  {
    level: 1,
    name: 'Rotting Kobold',
    hp: 28,
    atk: 1,
    xp: 19,
    meso: 1,
    img: 'img/monsters/monster_rottingkobold.webp',
  },
  {
    level: 1,
    name: 'Patrol Robot',
    hp: 30,
    atk: 1,
    xp: 21,
    meso: 1,
    img: 'img/monsters/monster_patrolrobot.webp',
  },
  {
    level: 1,
    name: 'Stone Golem',
    hp: 32,
    atk: 1,
    xp: 23,
    meso: 1,
    img: 'img/monsters/monster_stonegolem.webp',
  },
  {
    level: 1,
    name: 'Dark Stone Golem',
    hp: 34,
    atk: 1,
    xp: 25,
    meso: 1,
    img: 'img/monsters/monster_darkstonegolem.webp',
  },
  {
    level: 1,
    name: 'Mixed Golem',
    hp: 36,
    atk: 1,
    xp: 27,
    meso: 1,
    img: 'img/monsters/monster_mixedgolem.webp',
  },
  {
    level: 1,
    name: 'Oda Scout',
    hp: 38,
    atk: 1,
    xp: 29,
    meso: 1,
    img: 'img/monsters/monster_odascout.webp',
  },
  {
    level: 1,
    name: 'Oda Advanced Scout',
    hp: 40,
    atk: 1,
    xp: 31,
    meso: 1,
    img: 'img/monsters/monster_odaadvancedscout.webp',
  },
  {
    level: 1,
    name: '[BOSS] Mushmom',
    hp: 100,
    atk: 1,
    xp: 33,
    meso: 1,
    img: 'img/monsters/monster_mushmom.webp',
  },
  {
    level: 1,
    name: 'Oda Warrior',
    hp: 24,
    atk: 1,
    xp: 15,
    meso: 1,
    img: 'img/monsters/monster_odawarrior.webp',
  },
  {
    level: 1,
    name: 'Dust Box',
    hp: 26,
    atk: 1,
    xp: 17,
    meso: 1,
    img: 'img/monsters/monster_dustbox.webp',
  },
  {
    level: 1,
    name: 'Ghost Stump',
    hp: 28,
    atk: 1,
    xp: 19,
    meso: 1,
    img: 'img/monsters/monster_ghoststump.webp',
  },
  {
    level: 1,
    name: 'Giant Shadow Blade',
    hp: 30,
    atk: 1,
    xp: 21,
    meso: 1,
    img: 'img/monsters/monster_giantshadowblade.webp',
  },
  {
    level: 1,
    name: 'Evil Eye',
    hp: 32,
    atk: 1,
    xp: 23,
    meso: 1,
    img: 'img/monsters/monster_evileye.webp',
  },
  {
    level: 1,
    name: 'Ruins Sentinel',
    hp: 34,
    atk: 1,
    xp: 25,
    meso: 1,
    img: 'img/monsters/monster_ruinssentinel.webp',
  },
  {
    level: 1,
    name: 'Nefarious Monk Apprentice',
    hp: 36,
    atk: 1,
    xp: 27,
    meso: 1,
    img: 'img/monsters/monster_nefariousmonkapprentice.webp',
  },
  {
    level: 1,
    name: 'Nefarious Monk Master',
    hp: 38,
    atk: 1,
    xp: 29,
    meso: 1,
    img: 'img/monsters/monster_nefariousmonkmaster.webp',
  },
  {
    level: 1,
    name: 'Counts Swordsman',
    hp: 40,
    atk: 1,
    xp: 31,
    meso: 1,
    img: 'img/monsters/monster_countsswordsman.webp',
  },
  {
    level: 1,
    name: '[BOSS] Stumpy',
    hp: 100,
    atk: 1,
    xp: 33,
    meso: 1,
    img: 'img/monsters/monster_stumpy.webp',
  },
]

export const monsterVariables = {
  monsterHP: 0,
  monsterXP: 0,
  calcMonsterHP: 0,
  indexMonster: 0,
}

